Repository pedestal/pedestal, pull requests merged in 2024-06, with the labels that each got.

#851 Cleanup before 0.7.0-rc-1
  common/src/io/pedestal/internal.clj
  docs/modules/ROOT/pages/index.adoc
  service/src/io/pedestal/http/cors.clj
  tests/dev/playground.clj
  tests/test/io/pedestal/http/tracing_test.clj
  tests/test/io/pedestal/http_test.clj
  tests/test/io/pedestal/interceptor/observer_test.clj
  tests/test/io/pedestal/metrics/otel_test.clj
Labels: enhancement

#847 Correct content type in hello-world-content-types.adoc
  docs/modules/guides/examples/todo-api/src/main-complete.clj
  docs/modules/guides/examples/todo-api/src/main.clj
  docs/modules/guides/pages/hello-world-content-types.adoc
Labels: documentation

#852 Bump pretty to 3.0.0
  common/deps.edn
  common/src/io/pedestal/internal.clj
  deps.edn
  route/deps.edn
Labels: enhancement

#855 Re-add the clj-kondo support for io.pedestal.log macros
  log/deps.edn
  log/resources/clj-kondo.exports/io.pedestal/pedestal.log/config.edn
  log/resources/clj-kondo.exports/io.pedestal/pedestal.log/hooks/io/pedestal/log.clj_kondo
Labels: enhancement

#856 Fix bug in io.pedestal.http/json-body that corrupted the body of the response
  service/src/io/pedestal/http.clj
  tests/test/io/pedestal/http_test.clj
Labels: bug

#857 Update embedded jetty template
  docs/modules/guides/pages/embedded-template.adoc
  embedded/resources/io/pedestal/embedded/build/deps.tmpl
  embedded/resources/io/pedestal/embedded/config/logback.tmpl
  embedded/resources/io/pedestal/embedded/src/main.tmpl
  embedded/resources/io/pedestal/embedded/src/service.tmpl
  embedded/resources/io/pedestal/embedded/template.edn
  service/src/io/pedestal/http.clj
Labels: enhancement
