Repository pedestal/pedestal, pull requests merged in 2025-07, with the labels that each got.

#934 Fix a typo in hello-world.adoc
  docs/modules/guides/pages/hello-world.adoc
Labels: documentation

#935 Fix a typo in hello-world.adoc
  docs/modules/guides/pages/hello-world.adoc
Labels: documentation

#933 Include a prettier index.html page as part of the embedded template
  embedded/resources/io/pedestal/embedded/root/resources/public/app.css
  embedded/resources/io/pedestal/embedded/root/resources/public/index.html
  embedded/resources/io/pedestal/embedded/root/resources/public/pedestal-glyph.png
Labels: enhancement

#945 Convert JSON processing from cheshire to charred
  docs/modules/ROOT/pages/decision-log.adoc
  docs/modules/ROOT/pages/deprecations.adoc
  jetty/src/io/pedestal/http/jetty.clj
  service/deps.edn
  service/src/io/pedestal/http/body_params.clj
  service/src/io/pedestal/http/response.clj
  servlet/deps.edn
  tests/bench/io/pedestal/interceptor_chain_benchmark.clj
  tests/test/io/pedestal/http_test.clj
  tests/test/io/pedestal/service/hk_connector_test.clj
  tests/test/io/pedestal/service/hk_http_test.clj
Labels: enhancement

#951 body-params: don't attempt to parse if body is nil
  CHANGELOG.md
  service/src/io/pedestal/http/body_params.clj
  tests/test/io/pedestal/http/body_params_test.clj
Labels: bug, BREAKING CHANGE
